# Metody określania zmian struktur przestrzennych {#sec-lit}

<!-- Ten rozdział zawiera wyjaśnienie kontekstu pracy. -->

<!-- Pisząc ten rozdział proszę pomyśleć o osobach, które zupełnie nie znają opisywanej tematyki. -->
<!-- Należy tutaj krok po kroku wyjaśnić podstawowe koncepcje, istotność problemu, wyniki poprzednich podobnych badań, itd. -->
<!-- Ten rozdział obejmuje tylko kwestie, które już zostały wykonane przez inne osoby - nowe wyniki mają swoje miejsce w rozdziale [-@sec-wyniki]. -->

<!-- Każda kwestia opisana w tym rozdziale powinna być cytowana. -->
<!-- Dodatnie cytowania odbywa się poprzez uzupełnienie pliku `thesis.bib` zapisem w formacie BibTeX, a następnie dodanie nazwy referencji poprzedzonej znakiem `@`. -->
<!-- Przykładowo, zacytowanie książki Geocomputation with R odbywa się poprzez [@lovelace_geocomputation_2019]. -->
<!-- https://tex.stackexchange.com/questions/143/what-are-good-sites-to-find-citations-in-bibtex-format -->

<!-- W przypadku, gdy cytowanie zostało poprawnie wpisane oraz istnieje w pliku `thesis.bib` to bibliografia powinna się automatycznie wygenerować na końcu pracy. -->

<!-- W przypadku, gdy praca dyplomowa opisuje konkretny obszar to można po tym rozdziale stworzyć kolejny rozdział opisujący "obszar badań". -->

<!-- Ten i kolejne rozdziału moją mieć także podrozdziały. -->
<!-- Tworzenie podrozdziałów polega na stworzeniu nowej linii rozpoczynającej się od znaków `##` a następnie tytułu podrozdziału. -->
<!-- Dodatkowo w postaci `{#sec-}` można dodać skrót nazwy rozdziału/podrozdziału umożliwiający odnoszenie się do niego używając operatora `[-@sec]`. -->

<!-- ## Podrozdział {#sec-podr} -->

<!-- Przykładowo, "te kwestie zostały opisane w podrozdziale [-@sec-podr]". -->
<!-- Zwróć uwagę, że w ten sposób automatycznie tworzony jest odnośnik w pliku PDF. -->


<!-- cały rozdział o tym jakie są rodziny miar odległości, skąd się wywodzą, kto je stworzył i jak są liczone -->
<!-- * dodać rozdział 2 przegląd literatury - rozdział teoretyczny, opisujący czym są kompozycja, konfiguracja, macierze współwystępowania, wektor współwystępowania, metryki entropia, informacja wzajemna, na czym polega porównywanie dwóch obrazów i miary niepodobieństwa i przykłady. -->


W tym rozdziale zostaną kolejno opisane wszystkie zagadnienia kluczowe do pełnego zrozumienia tematyki określania zmian struktur przestrzennych w kontekście tematu zmian pokrycia terenu. W pierwszej kolejności zostanie opisana tematyka wykorzystania teorii informacji w analizie zmian pokrycia terenu. Omówione zostaną koncepcje przestrzennej kompozycji oraz konfiguracji, a także miary umożliwiające ich obliczenie. Następnie opisana zostanie idea reprezentacji rastrów w postaci macierzy i wektorów współwystępowania. W końcowej części rozdziału wyjaśnione zostaną zagadnienia miar odległości i podobieństwa oraz ich wykorzystania w celach analiz przestrzennych.


## Analiza zmian struktur przestrzennych

Zmiany i różnice w pokryciu terenu można analizować przy użyciu różnych metod. Najbardziej podstawowym sposobem jest prosta analiza ilościowa różnic w pokryciu terenu na analizowanym obszarze lub obszarach. Inny sposób, oparty o metody wywodzące się z dziedziny ekologii krajobrazów, polega na sprowadzeniu rastrów do postaci sygnatur przestrzennych. Sygnatury te stanowią statystyczny opis pewnych struktur przestrzennych występujących wewnątrz rastra [@nowosad_motif; @Jasiewicz_GeoPAT]. Takie podejście do analizy przestrzennej umożliwia między innymi ocenę różnic w przestrzennej kompozycji i konfiguracji analizowanych jednostek przestrzennych.

Najbardziej fundamentalną sygnaturą przestrzenną rastra jest kompozycja. Opisuje ona liczbę komórek każdej kategorii wewnątrz analizowanego rastra. Kolejną ważną sygnaturą przestrzenną jest konfiguracja, która w sposób liczbowy opisuje sąsiadowanie ze sobą poszczególnych kategorii rastra [@Gustafson1998]. Często w celu lepszej reprezentacji analizowanych rastrów możemy wykorzystywać także bardziej skomplikowane sygnatury. Przykładem sygnatury łączącej zarówno kompozycję, jak i konfigurację przestrzenną jest macierz współwystępowania. Jest to macierz o wymiarach k na k, gdzie k reprezentuje liczbę kategorii obecnych w analizowanym rastrze [@Haralick_1973; @Jasiewicz_GeoPAT]. Macierz tą możemy skonstruować poprzez zliczanie kolejno wszystkich par sąsiadujących ze sobą komórek w rastrze. Wewnątrz tej macierzy, wartości ułożone na przekątnych odnoszą się do kompozycji rastra, natomiast pozostałe do jego konfiguracji.

Na podstawie macierzy współwystępowania mogą zostać obliczone różne miary wywodzące się z dziedziny teorii informacji. Przykładem takiej miary jest entropia, która opisuje zróżnicowanie kompozycji rastra, czyli udziałów każdej z kategorii w rastrze. Kolejną miarą jest względna informacja wzajemna. Reprezentuje ona stopień sąsiadowania ze sobą kategorii w rastrze, czyli jego konfigurację przestrzenną. W celu porównywania ze sobą sygnatur w postaci dwuwymiarowej macierzy należy je sprowadzić do postaci jednowymiarowego wektora, a następnie przeprowadzić jego normalizację, tak aby wszystkie wartości sumowały się do 1. Taka postać pozwala na obliczanie miar odległości lub podobieństwa, pozwalających na porównywanie histogramów wartości [@Cha2007]. Miary te następnie pozwalają określić stopień zróżnicowania dwóch rastrów. Podejście to może być także wykorzystane w innych analizach przestrzennych, jak wyszukiwanie obszarów o podobnej strukturze przestrzennej, wykrywanie ich zmian oraz grupowanie obszarów o podobnej strukturze przestrzennej [@nowosad_motif].


## Miary odległości, podobieństwa i niepodobieństwa

Odległość i rozbieżność (inaczej podobieństwo) stanowią pewien policzalny stopień zróżnicowania pary obiektów. Największą różnicą między nimi jest to, że odległości są symetryczne, podczas gdy rozbieżności są niesymetryczne. Oznacza to, że wyłącznie dla miar odległości otrzymujemy identyczny wynik przy porównywaniu par obiektów A i B, jak i par B i A. Wybór odpowiedniej miary odległości lub podobieństwa zależy między innymi od rodzaju pomiaru lub sposobu reprezentacji obiektów [@Cha2007]. W związku z tym rodzi się pytanie, która z miar pozwala na uzyskanie najlepszych wyników dla danego zastosowania. Celem tej pracy, jak wspomniano we Wprowadzeniu, jest zatem wskazanie takich miar odległości lub podobieństwa, których zmiany wartości są najbardziej powiązane z postrzeganiem tych samych zmian przez człowieka.

Zagłębiając się w tematykę miar odległości i podobieństwa należy przede wszystkim wyjaśnić nieścisłości wynikających z samego ich nazewnictwa. Wykorzystanie w tej pracy samej nazwy "miary odległości" mogłoby być zinterpretowane jako grupa miar pozwalających na określenie rzeczywistego, mierzalnego dystansu pomiędzy dwoma obiektami, co nie jest zgodne z tym w jaki sposób miary te wykorzystane zostały w tej pracy. Nazwa "miary podobieństwa" jest natomiast sprzeczna w interpretacji z ludzką intuicją. Logiczne byłoby, że niskie wartości tej miary oznaczają małe podobieństwo, podczas gdy wysokie wartości oznaczają wysokie podobieństwo między porównywanymi obszarami. W rzeczywistości miary podobieństwa funkcjonują zupełnie przeciwnie. W związku z powyższymi problemami, wszystkie 45 miar odległości, podobieństwa oraz tych wywodzących się z dziedziny teorii informacji, które zostały wykorzystane w tej pracy będą dalej nazywane miarami niepodobieństwa. Nazwa ta, o ile pozornie trudniejsza do zrozumienia ma jednak istotną przewagę w kontekście wszelkich analiz. W tym kontekście, wraz ze wzrostem wartości miar niepodobieństwa rośnie różnica pomiędzy porównywanymi obszarami. Oznacza to, że niskie wartości miar niepodobieństwa wskazują na niskie niepodobieństwo, czyli niewielkie różnice między porównywanymi obszarami. Analogicznie, wysokie wartości miar niepodobieństwa wskazują na duże różnice między porównywanymi obszarami.

Na podstawie podobieństw syntaktycznych, wyróżnia się kilka grup rodzin miar niepodobieństwa: rodzina Minkowski (odległość euklidesowa, odległość Minkowskiego, odległość Manhattan), rodzina L1 (Canberra, Sorensen, Kulczynski), rodzina Intersection (Intersection, Wave Hedges, Ruzicka), rodzina Inner Product (Jaccard, Harmonic mean), rodzina Squared-chord (Fidelity, Matusita), rodzina Squared L2 (Clark, Pearson X2, Neyman X2), rodzina Shannon’s Entropy (Jensen-Shannon, Kullback-Leibler), a także miary będące połączeniem innych miar oraz miary wywodzące się z teorii informacji.

***tu mi się skończyły pomysły***
