project:
  type: book
  output-dir: docs

title: "Porównanie metod określania zmian struktury przestrzennej w kontekście analiz zmian kategorii pokrycia terenu"
titleeng: "Comparison of methods for determining changes in spatial patterns in the context of land cover change analyzes"
degreetype: "Praca magisterska" #"Engineer's thesis"
author: "Błażej Kościański"
major: "Geoinformacja" #"Geoinformation"
albumid: "444861"
year: "2023"

book:
  output-file: "koscianski_mgr"
  chapters:
    - index.qmd
    #- 00-oswiadczenie.qmd
    #- 00-abstrakt.qmd
    - 01-roz1.qmd
    - 02-roz2.qmd
    - 03-roz3.qmd
    - 04-roz4.qmd
    - 05-roz5.qmd

bibliography:
  - thesis.bib
  - packages.bib

format:
  pdf:
    template: amuthesis.tex
    keep-tex: true
    pdf-engine: pdflatex
    cite-method: biblatex
    fig-height: 3.8
    fig-width: 6.3
    fig-asp: 0.618  # 1 / phi
    fig-pos: 't'
    number-sections: true
